name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: moo
    - run: docker run -t moo -v $PWD:/moo bash -c "cd moo && pre-commit run -a"
